name: Rust - test docs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Test doc build for warnings
      run: RUSTDOCFLAGS="-D warnings" cargo doc

    - name: Test the docs
      run: cargo test --doc
