name: Rust - test default feature

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: cargo build --verbose

    - name: Run the integration tests for the default feature set
      run: cargo test --test integration

    - name: Run the lib tests for the default feature set
      run: cargo test --lib