name: Rust - test serde + chrono feature

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run the integration tests for the serde+chrono feature set
      run: cargo test --test integration --features chrono --features serde

    - name: Run the lib tests for the serde+chrono feature set
      run: cargo test --lib --features chrono --features serde