name: Rust - test clippy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Check the cargo version
      run: cargo --version

    - name: Check the clippy version
      run: cargo clippy --version

    - name: Test for any clippy warnings
      run: cargo clippy --all-targets -- -Dwarnings

    - name: Test a subset of clippy pedantic
      run: cargo clippy -- -W clippy::pedantic -A clippy::cast_possible_truncation -A clippy::cast_sign_loss -A clippy::single_match_else -A clippy::float_cmp -A clippy::missing_panics_doc -A clippy::must_use_candidate -A clippy::needless_pass_by_value -A clippy::struct_excessive_bools -A clippy::module_name_repetitions -A clippy::return_self_not_must_use  -Dwarnings




